services:
  service-inventory:
    build:
      context: ./service-inventory
      dockerfile: Dockerfile
    container_name: service-inventory
    network_mode: bridge
    ports:
      - "8081:8081"
    depends_on:
      - mysql
  mysql:
    image: 'mysql:latest'
    container_name: 'my-sql-v1'
    restart: always
    volumes:
      - './db-scripts/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      - MYSQL_ROOT_PASSWORD=elieta103
    ports:
      - '3306:3306'