CREATE DATABASE IF NOT EXISTS inventory;
use inventory;
CREATE TABLE IF NOT EXISTS products(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    code VARCHAR(50) NOT NULL UNIQUE,
    nameProduct VARCHAR(200) NOT NULL,
    stock INT NOT NULL,
    price DECIMAL(10,2) NOT NULL
);