spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/inventory
    username: root
    password: elieta103


logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
